#!/usr/bin/env php
<?php

/**
 * Load dependencies
 */
require __DIR__ . '/bootstrap.php';

/**
 * Parse the GL Spec
 */
$spec = new GLSpec;
$reader = new GLSpecReader;
$gen = new ExtGenerator;


// parse the GL spec
$reader->parse($spec, __DIR__ . '/data/gl.xml');

// import the gl spec into the generator
$gen->import($spec, 'gl', '4.1');

// parse the glfw header
$glfwparser = new GLFWHeaderParser;
$glfwparser->process(GEN_PATH_EXT . '/vendor/glfw/include/GLFW/glfw3.h', $gen);

// handle adjustments
$gen->adjust(PHPGlfwAdjustments\GLFWOptionalArgsAdjustments::class);
$gen->adjust(PHPGlfwAdjustments\GLFWGladLoader::class);

// build the extension
$gen->build(GEN_PATH_EXT . '/v2/');
